### ISSUE TITLE
Website style makeover

### ISSUE THREAD

**Issue by Omoorion** [Ido-Barnea/Chess-But-Better#267] opened 2024-03-29 16:41 UTC
- [ ] Make website prettier (background colors, main colors, etc).
- [ ] redesign elements such as buttons.
- [ ] use flex <div>s more often.
- [ ] refrain from using absolute unless necessary (for pawns, for example, it is probably necessary, for board squares who don't move, it isn't same thing for the board itself).
- [ ] make item alignment consistent (left-column for example).

**Comment by Ido-Barnea** [comment] 2024-03-29 16:49
Closing because the issue is too general. If you have any specific UI suggestions, open an issue for each (as was done before).

**Closed by Ido-Barnea** 2024-03-29 16:49 UTC
Labels: enhancement
